### PR TITLE
Fixed building

### PR DESCRIPTION
**Pull request by tofiki**
### CURRENTLY FAILS ON TEST SERVER, for no obvious reason lol

### CODE REVIEW

**Comment by tofiki** [comment]
it fails on JDK 8 but not on 11 or 16 , i need to fix it

**Comment by tofikarz** [comment]
> it fails on JDK 8 but not on 11 or 16 , i need to fix it

why does it only on JDK 8 have duplicate entries but not on other versions of JDK?

**Comment by tofiki** [comment]
> it fails on JDK 8 but not on 11 or 16 , i need to fix it

fixed but test server fails because fabric-api is not present (?)

**Comment by tofiki** [comment]
this again?

**Pull request closed without merging**
